# Generated by Django 4.0 on 2021-12-30 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fragatapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Place',
            new_name='Park',
        ),
    ]
